BOT_TOKEN = '7570931403:AAHqgmL6HufRS-8oThf6Aa-3hTW6raxO5ig'
# USERS = []
SYMBOL = 'SOL'
WAY = f'raw_data_{SYMBOL}'
EPOCHS = 1
WINDOW_HEIGHT = 1

PERIODS_RSI = 7
PERIOD_LONG_MACD = 13
PERIOD_SHORT_MACD = 6
PERIOD_SIGNAL_MACD = 9
STEP_BACK = max(PERIOD_SIGNAL_MACD, PERIOD_SHORT_MACD, PERIOD_LONG_MACD, PERIODS_RSI, WINDOW_HEIGHT)
