SYMBOL = 'ETH'
WAY = f'raw_data_{SYMBOL}'
EPOCHS = 1
WINDOW_HEIGHT = 1

PERIODS_RSI = 7
PERIOD_LONG_MACD = 13
PERIOD_SHORT_MACD = 6
PERIOD_SIGNAL_MACD = 9
STEP_BACK = max(PERIOD_SIGNAL_MACD, PERIOD_SHORT_MACD, PERIOD_LONG_MACD, PERIODS_RSI, WINDOW_HEIGHT)
